# Generated by Django 4.1.7 on 2023-03-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='short_url',
            field=models.CharField(max_length=50),
        ),
    ]
