# Generated by Django 4.1.7 on 2023-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0002_alter_tinyurl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinyurl',
            name='description',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
    ]
